#!/bin/bash

psql -U ${POSTGRES_USER} <<-END
    CREATE USER ${TEST_POSTGRES_USER} WITH PASSWORD '${TEST_POSTGRES_PASSWORD}';
    CREATE DATABASE ${TEST_POSTGRES_DB} OWNER ${TEST_POSTGRES_USER};
    GRANT ALL PRIVILEGES ON DATABASE ${TEST_POSTGRES_DB} TO ${TEST_POSTGRES_USER};
END

psql -U ${TEST_POSTGRES_USER} -d ${TEST_POSTGRES_DB} <<-END
    \i /docker-entrypoint-initdb.d/01.init.sql
END
